
import './globals.css'
import { Darker_Grotesque } from "next/font/google"


const darkerGrotesque=Darker_Grotesque({
  subsets:['latin'],
  weight:['600']
})


export const metadata = {
  title: 'DockerApp',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={darkerGrotesque.className} >{children}</body>
    </html>
  )
}
